// AUTO-GENERATED — DO NOT EDIT
// Generated by generate-doc-types.ts from schemas/frontmatter/*.schema.json
// Run 'npm run build:decap' to regenerate

export const DOC_TYPES = [
  'adr',
  'capability',
  'flow',
  'guide',
  'meeting',
  'policy',
  'postmortem',
  'prd',
  'process',
  'reference',
  'report',
  'runbook',
  'sop',
  'standard',
  'system',
  'tdd',
  'wiki',
] as const;

export type DocType = typeof DOC_TYPES[number];

export function isDocType(value: string): value is DocType {
  return (DOC_TYPES as readonly string[]).includes(value);
}

export const TEMPLATE_REGISTRY: Record<DocType, { folder: string }> = {
  'adr': { folder: '90_Architecture/ADRs' },
  'capability': { folder: '110_Capabilities' },
  'flow': { folder: '100_Products/Flows' },
  'guide': { folder: '55_Guides' },
  'meeting': { folder: '60_Meetings' },
  'policy': { folder: '10_Policies' },
  'postmortem': { folder: '85_Postmortems' },
  'prd': { folder: '100_Products/PRDs' },
  'process': { folder: '30_Processes' },
  'reference': { folder: '200_References' },
  'report': { folder: '80_Reports' },
  'runbook': { folder: '50_Runbooks' },
  'sop': { folder: '40_SOPs' },
  'standard': { folder: '20_Standards' },
  'system': { folder: '70_Systems' },
  'tdd': { folder: '90_Architecture/TDDs' },
  'wiki': { folder: '75_Wikis' },
};
