#!/usr/bin/env tsx
/**
 * Generate doc-types.generated.ts from JSON schemas
 *
 * Reads schemas/frontmatter/*.schema.json and extracts type metadata
 * to generate TypeScript constants for browser validation.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '../../..');
const SCHEMAS_DIR = path.join(PROJECT_ROOT, 'schemas/frontmatter');
const OUTPUT_PATH = path.join(__dirname, 'doc-types.generated.ts');

interface SchemaMetadata {
  type: string;
  folder: string;
}

function main() {
  console.log('Generating doc types from schemas...');

  if (!fs.existsSync(SCHEMAS_DIR)) {
    console.error(`Schemas directory not found: ${SCHEMAS_DIR}`);
    process.exit(1);
  }

  const schemaFiles = fs.readdirSync(SCHEMAS_DIR)
    .filter(f => f.endsWith('.schema.json') && f !== 'base.schema.json')
    .sort();

  const metadata: SchemaMetadata[] = [];

  for (const file of schemaFiles) {
    const schemaPath = path.join(SCHEMAS_DIR, file);
    const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));

    const type = schema.properties?.type?.const;
    const folder = schema['x-synapse']?.folder;

    if (!type) {
      console.warn(`Warning: Skipping ${file}: no properties.type.const`);
      continue;
    }

    if (!folder) {
      console.warn(`Warning: Skipping ${file}: no x-synapse.folder`);
      continue;
    }

    metadata.push({ type, folder });
  }

  metadata.sort((a, b) => a.type.localeCompare(b.type));

  const typesArray = metadata.map(m => `  '${m.type}'`).join(',\n');
  const registryEntries = metadata.map(m =>
    `  '${m.type}': { folder: '${m.folder}' }`
  ).join(',\n');

  const output = `// AUTO-GENERATED — DO NOT EDIT
// Generated by generate-doc-types.ts from schemas/frontmatter/*.schema.json
// Run 'npm run build:decap' to regenerate

export const DOC_TYPES = [
${typesArray},
] as const;

export type DocType = typeof DOC_TYPES[number];

export function isDocType(value: string): value is DocType {
  return (DOC_TYPES as readonly string[]).includes(value);
}

export const TEMPLATE_REGISTRY: Record<DocType, { folder: string }> = {
${registryEntries},
};
`;

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${metadata.length} doc types -> doc-types.generated.ts`);
}

main();
